/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as NewRouteRouteImport } from './routes/new/route'
import { Route as OldRouteRouteImport } from './routes/old/route'
import { Route as SourceRouteImport } from './routes/source'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApiRouteImport } from './routes/_app/api'
import { Route as AppChangelogRouteImport } from './routes/_app/changelog'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppMethodologyRouteImport } from './routes/_app/methodology'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiLedgerDotcsvRouteImport } from './routes/api/ledger[.]csv'
import { Route as ApiLedgerDotjsonRouteImport } from './routes/api/ledger[.]json'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as NewSplatRouteImport } from './routes/new/$'
import { Route as OldIndexRouteImport } from './routes/old/index'
import { Route as OldSourceRouteImport } from './routes/old/source'
import { Route as AppBenchmarksIndexRouteImport } from './routes/_app/benchmarks.index'
import { Route as AppBenchmarksIdRouteImport } from './routes/_app/benchmarks.$id'
import { Route as AppLabsIndexRouteImport } from './routes/_app/labs.index'
import { Route as AppLabsIdRouteImport } from './routes/_app/labs.$id'
import { Route as AppModelsIndexRouteImport } from './routes/_app/models.index'
import { Route as AppModelsSlugRouteImport } from './routes/_app/models.$slug'
import { Route as AppNewsIndexRouteImport } from './routes/_app/news.index'
import { Route as AppNewsIdRouteImport } from './routes/_app/news.$id'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1LeaderboardRouteImport } from './routes/api/v1/leaderboard'
import { Route as OldModelsSlugRouteImport } from './routes/old/models.$slug'
import { Route as OldNewsIndexRouteImport } from './routes/old/news.index'
import { Route as OldNewsIdRouteImport } from './routes/old/news.$id'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OldRouteRoute = OldRouteRouteImport.update({
  id: '/old',
  path: '/old',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMethodologyRoute = AppMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerDotcsvRoute = ApiLedgerDotcsvRouteImport.update({
  id: '/api/ledger.csv',
  path: '/api/ledger.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerDotjsonRoute = ApiLedgerDotjsonRouteImport.update({
  id: '/api/ledger.json',
  path: '/api/ledger.json',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewSplatRoute = NewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => NewRouteRoute,
} as any)
const OldIndexRoute = OldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OldRouteRoute,
} as any)
const OldSourceRoute = OldSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => OldRouteRoute,
} as any)
const AppBenchmarksIndexRoute = AppBenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBenchmarksIdRoute = AppBenchmarksIdRouteImport.update({
  id: '/benchmarks/$id',
  path: '/benchmarks/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabsIndexRoute = AppLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabsIdRoute = AppLabsIdRouteImport.update({
  id: '/labs/$id',
  path: '/labs/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsSlugRoute = AppModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewsIdRoute = AppNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LeaderboardRoute = ApiV1LeaderboardRouteImport.update({
  id: '/api/v1/leaderboard',
  path: '/api/v1/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OldModelsSlugRoute = OldModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => OldRouteRoute,
} as any)
const OldNewsIndexRoute = OldNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => OldRouteRoute,
} as any)
const OldNewsIdRoute = OldNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => OldRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/new': typeof NewRouteRouteWithChildren
  '/old': typeof OldRouteRouteWithChildren
  '/source': typeof SourceRoute
  '/api': typeof AppApiRoute
  '/changelog': typeof AppChangelogRoute
  '/compare': typeof AppCompareRoute
  '/methodology': typeof AppMethodologyRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/new/$': typeof NewSplatRoute
  '/old/source': typeof OldSourceRoute
  '/new/': typeof NewIndexRoute
  '/old/': typeof OldIndexRoute
  '/benchmarks/$id': typeof AppBenchmarksIdRoute
  '/labs/$id': typeof AppLabsIdRoute
  '/models/$slug': typeof AppModelsSlugRoute
  '/news/$id': typeof AppNewsIdRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/old/models/$slug': typeof OldModelsSlugRoute
  '/old/news/$id': typeof OldNewsIdRoute
  '/benchmarks/': typeof AppBenchmarksIndexRoute
  '/labs/': typeof AppLabsIndexRoute
  '/models/': typeof AppModelsIndexRoute
  '/news/': typeof AppNewsIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/old/news/': typeof OldNewsIndexRoute
}
export interface FileRoutesByTo {
  '/source': typeof SourceRoute
  '/api': typeof AppApiRoute
  '/changelog': typeof AppChangelogRoute
  '/compare': typeof AppCompareRoute
  '/methodology': typeof AppMethodologyRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/new/$': typeof NewSplatRoute
  '/old/source': typeof OldSourceRoute
  '/': typeof AppIndexRoute
  '/new': typeof NewIndexRoute
  '/old': typeof OldIndexRoute
  '/benchmarks/$id': typeof AppBenchmarksIdRoute
  '/labs/$id': typeof AppLabsIdRoute
  '/models/$slug': typeof AppModelsSlugRoute
  '/news/$id': typeof AppNewsIdRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/old/models/$slug': typeof OldModelsSlugRoute
  '/old/news/$id': typeof OldNewsIdRoute
  '/benchmarks': typeof AppBenchmarksIndexRoute
  '/labs': typeof AppLabsIndexRoute
  '/models': typeof AppModelsIndexRoute
  '/news': typeof AppNewsIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/old/news': typeof OldNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/new': typeof NewRouteRouteWithChildren
  '/old': typeof OldRouteRouteWithChildren
  '/source': typeof SourceRoute
  '/_app/api': typeof AppApiRoute
  '/_app/changelog': typeof AppChangelogRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/methodology': typeof AppMethodologyRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/new/$': typeof NewSplatRoute
  '/old/source': typeof OldSourceRoute
  '/_app/': typeof AppIndexRoute
  '/new/': typeof NewIndexRoute
  '/old/': typeof OldIndexRoute
  '/_app/benchmarks/$id': typeof AppBenchmarksIdRoute
  '/_app/labs/$id': typeof AppLabsIdRoute
  '/_app/models/$slug': typeof AppModelsSlugRoute
  '/_app/news/$id': typeof AppNewsIdRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/old/models/$slug': typeof OldModelsSlugRoute
  '/old/news/$id': typeof OldNewsIdRoute
  '/_app/benchmarks/': typeof AppBenchmarksIndexRoute
  '/_app/labs/': typeof AppLabsIndexRoute
  '/_app/models/': typeof AppModelsIndexRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/old/news/': typeof OldNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/old'
    | '/source'
    | '/api'
    | '/changelog'
    | '/compare'
    | '/methodology'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/new/$'
    | '/old/source'
    | '/new/'
    | '/old/'
    | '/benchmarks/$id'
    | '/labs/$id'
    | '/models/$slug'
    | '/news/$id'
    | '/api/v1/leaderboard'
    | '/old/models/$slug'
    | '/old/news/$id'
    | '/benchmarks/'
    | '/labs/'
    | '/models/'
    | '/news/'
    | '/api/v1/'
    | '/old/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/source'
    | '/api'
    | '/changelog'
    | '/compare'
    | '/methodology'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/new/$'
    | '/old/source'
    | '/'
    | '/new'
    | '/old'
    | '/benchmarks/$id'
    | '/labs/$id'
    | '/models/$slug'
    | '/news/$id'
    | '/api/v1/leaderboard'
    | '/old/models/$slug'
    | '/old/news/$id'
    | '/benchmarks'
    | '/labs'
    | '/models'
    | '/news'
    | '/api/v1'
    | '/old/news'
  id:
    | '__root__'
    | '/_app'
    | '/new'
    | '/old'
    | '/source'
    | '/_app/api'
    | '/_app/changelog'
    | '/_app/compare'
    | '/_app/methodology'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/new/$'
    | '/old/source'
    | '/_app/'
    | '/new/'
    | '/old/'
    | '/_app/benchmarks/$id'
    | '/_app/labs/$id'
    | '/_app/models/$slug'
    | '/_app/news/$id'
    | '/api/v1/leaderboard'
    | '/old/models/$slug'
    | '/old/news/$id'
    | '/_app/benchmarks/'
    | '/_app/labs/'
    | '/_app/models/'
    | '/_app/news/'
    | '/api/v1/'
    | '/old/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  NewRouteRoute: typeof NewRouteRouteWithChildren
  OldRouteRoute: typeof OldRouteRouteWithChildren
  SourceRoute: typeof SourceRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiLedgerDotcsvRoute: typeof ApiLedgerDotcsvRoute
  ApiLedgerDotjsonRoute: typeof ApiLedgerDotjsonRoute
  ApiV1LeaderboardRoute: typeof ApiV1LeaderboardRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old': {
      id: '/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof OldRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/changelog': {
      id: '/_app/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/methodology': {
      id: '/_app/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof AppMethodologyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger.csv': {
      id: '/api/ledger.csv'
      path: '/api/ledger.csv'
      fullPath: '/api/ledger.csv'
      preLoaderRoute: typeof ApiLedgerDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger.json': {
      id: '/api/ledger.json'
      path: '/api/ledger.json'
      fullPath: '/api/ledger.json'
      preLoaderRoute: typeof ApiLedgerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/new/$': {
      id: '/new/$'
      path: '/$'
      fullPath: '/new/$'
      preLoaderRoute: typeof NewSplatRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/old/': {
      id: '/old/'
      path: '/'
      fullPath: '/old/'
      preLoaderRoute: typeof OldIndexRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/old/source': {
      id: '/old/source'
      path: '/source'
      fullPath: '/old/source'
      preLoaderRoute: typeof OldSourceRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/_app/benchmarks/': {
      id: '/_app/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof AppBenchmarksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/benchmarks/$id': {
      id: '/_app/benchmarks/$id'
      path: '/benchmarks/$id'
      fullPath: '/benchmarks/$id'
      preLoaderRoute: typeof AppBenchmarksIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/labs/': {
      id: '/_app/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AppLabsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/labs/$id': {
      id: '/_app/labs/$id'
      path: '/labs/$id'
      fullPath: '/labs/$id'
      preLoaderRoute: typeof AppLabsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/': {
      id: '/_app/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/$slug': {
      id: '/_app/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof AppModelsSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/news/$id': {
      id: '/_app/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof AppNewsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/leaderboard': {
      id: '/api/v1/leaderboard'
      path: '/api/v1/leaderboard'
      fullPath: '/api/v1/leaderboard'
      preLoaderRoute: typeof ApiV1LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/models/$slug': {
      id: '/old/models/$slug'
      path: '/models/$slug'
      fullPath: '/old/models/$slug'
      preLoaderRoute: typeof OldModelsSlugRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/old/news/': {
      id: '/old/news/'
      path: '/news'
      fullPath: '/old/news/'
      preLoaderRoute: typeof OldNewsIndexRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/old/news/$id': {
      id: '/old/news/$id'
      path: '/news/$id'
      fullPath: '/old/news/$id'
      preLoaderRoute: typeof OldNewsIdRouteImport
      parentRoute: typeof OldRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppApiRoute: typeof AppApiRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppCompareRoute: typeof AppCompareRoute
  AppMethodologyRoute: typeof AppMethodologyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBenchmarksIdRoute: typeof AppBenchmarksIdRoute
  AppLabsIdRoute: typeof AppLabsIdRoute
  AppModelsSlugRoute: typeof AppModelsSlugRoute
  AppNewsIdRoute: typeof AppNewsIdRoute
  AppBenchmarksIndexRoute: typeof AppBenchmarksIndexRoute
  AppLabsIndexRoute: typeof AppLabsIndexRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppApiRoute: AppApiRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppCompareRoute: AppCompareRoute,
  AppMethodologyRoute: AppMethodologyRoute,
  AppIndexRoute: AppIndexRoute,
  AppBenchmarksIdRoute: AppBenchmarksIdRoute,
  AppLabsIdRoute: AppLabsIdRoute,
  AppModelsSlugRoute: AppModelsSlugRoute,
  AppNewsIdRoute: AppNewsIdRoute,
  AppBenchmarksIndexRoute: AppBenchmarksIndexRoute,
  AppLabsIndexRoute: AppLabsIndexRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface NewRouteRouteChildren {
  NewSplatRoute: typeof NewSplatRoute
  NewIndexRoute: typeof NewIndexRoute
}

const NewRouteRouteChildren: NewRouteRouteChildren = {
  NewSplatRoute: NewSplatRoute,
  NewIndexRoute: NewIndexRoute,
}

const NewRouteRouteWithChildren = NewRouteRoute._addFileChildren(
  NewRouteRouteChildren,
)

interface OldRouteRouteChildren {
  OldSourceRoute: typeof OldSourceRoute
  OldIndexRoute: typeof OldIndexRoute
  OldModelsSlugRoute: typeof OldModelsSlugRoute
  OldNewsIdRoute: typeof OldNewsIdRoute
  OldNewsIndexRoute: typeof OldNewsIndexRoute
}

const OldRouteRouteChildren: OldRouteRouteChildren = {
  OldSourceRoute: OldSourceRoute,
  OldIndexRoute: OldIndexRoute,
  OldModelsSlugRoute: OldModelsSlugRoute,
  OldNewsIdRoute: OldNewsIdRoute,
  OldNewsIndexRoute: OldNewsIndexRoute,
}

const OldRouteRouteWithChildren = OldRouteRoute._addFileChildren(
  OldRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  NewRouteRoute: NewRouteRouteWithChildren,
  OldRouteRoute: OldRouteRouteWithChildren,
  SourceRoute: SourceRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiLedgerDotcsvRoute: ApiLedgerDotcsvRoute,
  ApiLedgerDotjsonRoute: ApiLedgerDotjsonRoute,
  ApiV1LeaderboardRoute: ApiV1LeaderboardRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
