/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as NewRouteRouteImport } from './routes/new/route'
import { Route as OldRouteRouteImport } from './routes/old/route'
import { Route as SourceRouteImport } from './routes/source'
import { Route as V3RouteRouteImport } from './routes/v3/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppApiRouteImport } from './routes/_app/api'
import { Route as AppChangelogRouteImport } from './routes/_app/changelog'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppMethodologyRouteImport } from './routes/_app/methodology'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiLedgerDotcsvRouteImport } from './routes/api/ledger[.]csv'
import { Route as ApiLedgerDotjsonRouteImport } from './routes/api/ledger[.]json'
import { Route as ApiTRouteImport } from './routes/api/t'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as NewSplatRouteImport } from './routes/new/$'
import { Route as OldIndexRouteImport } from './routes/old/index'
import { Route as OldSourceRouteImport } from './routes/old/source'
import { Route as V3IndexRouteImport } from './routes/v3/index'
import { Route as V3ChangelogRouteImport } from './routes/v3/changelog'
import { Route as V3CompareRouteImport } from './routes/v3/compare'
import { Route as V3MethodologyRouteImport } from './routes/v3/methodology'
import { Route as AppBenchmarksIndexRouteImport } from './routes/_app/benchmarks.index'
import { Route as AppBenchmarksIdRouteImport } from './routes/_app/benchmarks.$id'
import { Route as AppLabsIndexRouteImport } from './routes/_app/labs.index'
import { Route as AppLabsIdRouteImport } from './routes/_app/labs.$id'
import { Route as AppModelsIndexRouteImport } from './routes/_app/models.index'
import { Route as AppModelsSlugRouteImport } from './routes/_app/models.$slug'
import { Route as AppNewsIndexRouteImport } from './routes/_app/news.index'
import { Route as AppNewsIdRouteImport } from './routes/_app/news.$id'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin/bootstrap'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1LeaderboardRouteImport } from './routes/api/v1/leaderboard'
import { Route as OldModelsSlugRouteImport } from './routes/old/models.$slug'
import { Route as OldNewsIndexRouteImport } from './routes/old/news.index'
import { Route as OldNewsIdRouteImport } from './routes/old/news.$id'
import { Route as V3BenchmarksIndexRouteImport } from './routes/v3/benchmarks.index'
import { Route as V3BenchmarksIdRouteImport } from './routes/v3/benchmarks.$id'
import { Route as V3LabsIndexRouteImport } from './routes/v3/labs.index'
import { Route as V3LabsIdRouteImport } from './routes/v3/labs.$id'
import { Route as V3ModelsIndexRouteImport } from './routes/v3/models.index'
import { Route as V3ModelsSlugRouteImport } from './routes/v3/models.$slug'
import { Route as V3NewsIndexRouteImport } from './routes/v3/news.index'
import { Route as V3NewsIdRouteImport } from './routes/v3/news.$id'
import { Route as ApiAdminAuthSplatRouteImport } from './routes/api/admin/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRouteRoute = NewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OldRouteRoute = OldRouteRouteImport.update({
  id: '/old',
  path: '/old',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const V3RouteRoute = V3RouteRouteImport.update({
  id: '/v3',
  path: '/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiRoute = AppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMethodologyRoute = AppMethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerDotcsvRoute = ApiLedgerDotcsvRouteImport.update({
  id: '/api/ledger.csv',
  path: '/api/ledger.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerDotjsonRoute = ApiLedgerDotjsonRouteImport.update({
  id: '/api/ledger.json',
  path: '/api/ledger.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTRoute = ApiTRouteImport.update({
  id: '/api/t',
  path: '/api/t',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewRouteRoute,
} as any)
const NewSplatRoute = NewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => NewRouteRoute,
} as any)
const OldIndexRoute = OldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OldRouteRoute,
} as any)
const OldSourceRoute = OldSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => OldRouteRoute,
} as any)
const V3IndexRoute = V3IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3ChangelogRoute = V3ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3CompareRoute = V3CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3MethodologyRoute = V3MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => V3RouteRoute,
} as any)
const AppBenchmarksIndexRoute = AppBenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBenchmarksIdRoute = AppBenchmarksIdRouteImport.update({
  id: '/benchmarks/$id',
  path: '/benchmarks/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabsIndexRoute = AppLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabsIdRoute = AppLabsIdRouteImport.update({
  id: '/labs/$id',
  path: '/labs/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsSlugRoute = AppModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewsIdRoute = AppNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LeaderboardRoute = ApiV1LeaderboardRouteImport.update({
  id: '/api/v1/leaderboard',
  path: '/api/v1/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OldModelsSlugRoute = OldModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => OldRouteRoute,
} as any)
const OldNewsIndexRoute = OldNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => OldRouteRoute,
} as any)
const OldNewsIdRoute = OldNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => OldRouteRoute,
} as any)
const V3BenchmarksIndexRoute = V3BenchmarksIndexRouteImport.update({
  id: '/benchmarks/',
  path: '/benchmarks/',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3BenchmarksIdRoute = V3BenchmarksIdRouteImport.update({
  id: '/benchmarks/$id',
  path: '/benchmarks/$id',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3LabsIndexRoute = V3LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3LabsIdRoute = V3LabsIdRouteImport.update({
  id: '/labs/$id',
  path: '/labs/$id',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3ModelsIndexRoute = V3ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3ModelsSlugRoute = V3ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3NewsIndexRoute = V3NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => V3RouteRoute,
} as any)
const V3NewsIdRoute = V3NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => V3RouteRoute,
} as any)
const ApiAdminAuthSplatRoute = ApiAdminAuthSplatRouteImport.update({
  id: '/api/admin/auth/$',
  path: '/api/admin/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/new': typeof NewRouteRouteWithChildren
  '/old': typeof OldRouteRouteWithChildren
  '/v3': typeof V3RouteRouteWithChildren
  '/source': typeof SourceRoute
  '/api': typeof AppApiRoute
  '/changelog': typeof AppChangelogRoute
  '/compare': typeof AppCompareRoute
  '/methodology': typeof AppMethodologyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/api/t': typeof ApiTRoute
  '/new/$': typeof NewSplatRoute
  '/old/source': typeof OldSourceRoute
  '/v3/changelog': typeof V3ChangelogRoute
  '/v3/compare': typeof V3CompareRoute
  '/v3/methodology': typeof V3MethodologyRoute
  '/admin/': typeof AdminIndexRoute
  '/new/': typeof NewIndexRoute
  '/old/': typeof OldIndexRoute
  '/v3/': typeof V3IndexRoute
  '/benchmarks/$id': typeof AppBenchmarksIdRoute
  '/labs/$id': typeof AppLabsIdRoute
  '/models/$slug': typeof AppModelsSlugRoute
  '/news/$id': typeof AppNewsIdRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/old/models/$slug': typeof OldModelsSlugRoute
  '/old/news/$id': typeof OldNewsIdRoute
  '/v3/benchmarks/$id': typeof V3BenchmarksIdRoute
  '/v3/labs/$id': typeof V3LabsIdRoute
  '/v3/models/$slug': typeof V3ModelsSlugRoute
  '/v3/news/$id': typeof V3NewsIdRoute
  '/benchmarks/': typeof AppBenchmarksIndexRoute
  '/labs/': typeof AppLabsIndexRoute
  '/models/': typeof AppModelsIndexRoute
  '/news/': typeof AppNewsIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/old/news/': typeof OldNewsIndexRoute
  '/v3/benchmarks/': typeof V3BenchmarksIndexRoute
  '/v3/labs/': typeof V3LabsIndexRoute
  '/v3/models/': typeof V3ModelsIndexRoute
  '/v3/news/': typeof V3NewsIndexRoute
  '/api/admin/auth/$': typeof ApiAdminAuthSplatRoute
}
export interface FileRoutesByTo {
  '/source': typeof SourceRoute
  '/api': typeof AppApiRoute
  '/changelog': typeof AppChangelogRoute
  '/compare': typeof AppCompareRoute
  '/methodology': typeof AppMethodologyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/api/t': typeof ApiTRoute
  '/new/$': typeof NewSplatRoute
  '/old/source': typeof OldSourceRoute
  '/v3/changelog': typeof V3ChangelogRoute
  '/v3/compare': typeof V3CompareRoute
  '/v3/methodology': typeof V3MethodologyRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/new': typeof NewIndexRoute
  '/old': typeof OldIndexRoute
  '/v3': typeof V3IndexRoute
  '/benchmarks/$id': typeof AppBenchmarksIdRoute
  '/labs/$id': typeof AppLabsIdRoute
  '/models/$slug': typeof AppModelsSlugRoute
  '/news/$id': typeof AppNewsIdRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/old/models/$slug': typeof OldModelsSlugRoute
  '/old/news/$id': typeof OldNewsIdRoute
  '/v3/benchmarks/$id': typeof V3BenchmarksIdRoute
  '/v3/labs/$id': typeof V3LabsIdRoute
  '/v3/models/$slug': typeof V3ModelsSlugRoute
  '/v3/news/$id': typeof V3NewsIdRoute
  '/benchmarks': typeof AppBenchmarksIndexRoute
  '/labs': typeof AppLabsIndexRoute
  '/models': typeof AppModelsIndexRoute
  '/news': typeof AppNewsIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/old/news': typeof OldNewsIndexRoute
  '/v3/benchmarks': typeof V3BenchmarksIndexRoute
  '/v3/labs': typeof V3LabsIndexRoute
  '/v3/models': typeof V3ModelsIndexRoute
  '/v3/news': typeof V3NewsIndexRoute
  '/api/admin/auth/$': typeof ApiAdminAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/new': typeof NewRouteRouteWithChildren
  '/old': typeof OldRouteRouteWithChildren
  '/v3': typeof V3RouteRouteWithChildren
  '/source': typeof SourceRoute
  '/_app/api': typeof AppApiRoute
  '/_app/changelog': typeof AppChangelogRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/methodology': typeof AppMethodologyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/api/t': typeof ApiTRoute
  '/new/$': typeof NewSplatRoute
  '/old/source': typeof OldSourceRoute
  '/v3/changelog': typeof V3ChangelogRoute
  '/v3/compare': typeof V3CompareRoute
  '/v3/methodology': typeof V3MethodologyRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/new/': typeof NewIndexRoute
  '/old/': typeof OldIndexRoute
  '/v3/': typeof V3IndexRoute
  '/_app/benchmarks/$id': typeof AppBenchmarksIdRoute
  '/_app/labs/$id': typeof AppLabsIdRoute
  '/_app/models/$slug': typeof AppModelsSlugRoute
  '/_app/news/$id': typeof AppNewsIdRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/old/models/$slug': typeof OldModelsSlugRoute
  '/old/news/$id': typeof OldNewsIdRoute
  '/v3/benchmarks/$id': typeof V3BenchmarksIdRoute
  '/v3/labs/$id': typeof V3LabsIdRoute
  '/v3/models/$slug': typeof V3ModelsSlugRoute
  '/v3/news/$id': typeof V3NewsIdRoute
  '/_app/benchmarks/': typeof AppBenchmarksIndexRoute
  '/_app/labs/': typeof AppLabsIndexRoute
  '/_app/models/': typeof AppModelsIndexRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/old/news/': typeof OldNewsIndexRoute
  '/v3/benchmarks/': typeof V3BenchmarksIndexRoute
  '/v3/labs/': typeof V3LabsIndexRoute
  '/v3/models/': typeof V3ModelsIndexRoute
  '/v3/news/': typeof V3NewsIndexRoute
  '/api/admin/auth/$': typeof ApiAdminAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/new'
    | '/old'
    | '/v3'
    | '/source'
    | '/api'
    | '/changelog'
    | '/compare'
    | '/methodology'
    | '/admin/login'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/api/t'
    | '/new/$'
    | '/old/source'
    | '/v3/changelog'
    | '/v3/compare'
    | '/v3/methodology'
    | '/admin/'
    | '/new/'
    | '/old/'
    | '/v3/'
    | '/benchmarks/$id'
    | '/labs/$id'
    | '/models/$slug'
    | '/news/$id'
    | '/api/admin/bootstrap'
    | '/api/admin/stats'
    | '/api/v1/leaderboard'
    | '/old/models/$slug'
    | '/old/news/$id'
    | '/v3/benchmarks/$id'
    | '/v3/labs/$id'
    | '/v3/models/$slug'
    | '/v3/news/$id'
    | '/benchmarks/'
    | '/labs/'
    | '/models/'
    | '/news/'
    | '/api/v1/'
    | '/old/news/'
    | '/v3/benchmarks/'
    | '/v3/labs/'
    | '/v3/models/'
    | '/v3/news/'
    | '/api/admin/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/source'
    | '/api'
    | '/changelog'
    | '/compare'
    | '/methodology'
    | '/admin/login'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/api/t'
    | '/new/$'
    | '/old/source'
    | '/v3/changelog'
    | '/v3/compare'
    | '/v3/methodology'
    | '/'
    | '/admin'
    | '/new'
    | '/old'
    | '/v3'
    | '/benchmarks/$id'
    | '/labs/$id'
    | '/models/$slug'
    | '/news/$id'
    | '/api/admin/bootstrap'
    | '/api/admin/stats'
    | '/api/v1/leaderboard'
    | '/old/models/$slug'
    | '/old/news/$id'
    | '/v3/benchmarks/$id'
    | '/v3/labs/$id'
    | '/v3/models/$slug'
    | '/v3/news/$id'
    | '/benchmarks'
    | '/labs'
    | '/models'
    | '/news'
    | '/api/v1'
    | '/old/news'
    | '/v3/benchmarks'
    | '/v3/labs'
    | '/v3/models'
    | '/v3/news'
    | '/api/admin/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/new'
    | '/old'
    | '/v3'
    | '/source'
    | '/_app/api'
    | '/_app/changelog'
    | '/_app/compare'
    | '/_app/methodology'
    | '/admin/login'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/api/t'
    | '/new/$'
    | '/old/source'
    | '/v3/changelog'
    | '/v3/compare'
    | '/v3/methodology'
    | '/_app/'
    | '/admin/'
    | '/new/'
    | '/old/'
    | '/v3/'
    | '/_app/benchmarks/$id'
    | '/_app/labs/$id'
    | '/_app/models/$slug'
    | '/_app/news/$id'
    | '/api/admin/bootstrap'
    | '/api/admin/stats'
    | '/api/v1/leaderboard'
    | '/old/models/$slug'
    | '/old/news/$id'
    | '/v3/benchmarks/$id'
    | '/v3/labs/$id'
    | '/v3/models/$slug'
    | '/v3/news/$id'
    | '/_app/benchmarks/'
    | '/_app/labs/'
    | '/_app/models/'
    | '/_app/news/'
    | '/api/v1/'
    | '/old/news/'
    | '/v3/benchmarks/'
    | '/v3/labs/'
    | '/v3/models/'
    | '/v3/news/'
    | '/api/admin/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  NewRouteRoute: typeof NewRouteRouteWithChildren
  OldRouteRoute: typeof OldRouteRouteWithChildren
  V3RouteRoute: typeof V3RouteRouteWithChildren
  SourceRoute: typeof SourceRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiLedgerDotcsvRoute: typeof ApiLedgerDotcsvRoute
  ApiLedgerDotjsonRoute: typeof ApiLedgerDotjsonRoute
  ApiTRoute: typeof ApiTRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiV1LeaderboardRoute: typeof ApiV1LeaderboardRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiAdminAuthSplatRoute: typeof ApiAdminAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old': {
      id: '/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof OldRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3': {
      id: '/v3'
      path: '/v3'
      fullPath: '/v3'
      preLoaderRoute: typeof V3RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/api': {
      id: '/_app/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof AppApiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/changelog': {
      id: '/_app/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/methodology': {
      id: '/_app/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof AppMethodologyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger.csv': {
      id: '/api/ledger.csv'
      path: '/api/ledger.csv'
      fullPath: '/api/ledger.csv'
      preLoaderRoute: typeof ApiLedgerDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger.json': {
      id: '/api/ledger.json'
      path: '/api/ledger.json'
      fullPath: '/api/ledger.json'
      preLoaderRoute: typeof ApiLedgerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t': {
      id: '/api/t'
      path: '/api/t'
      fullPath: '/api/t'
      preLoaderRoute: typeof ApiTRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/new/$': {
      id: '/new/$'
      path: '/$'
      fullPath: '/new/$'
      preLoaderRoute: typeof NewSplatRouteImport
      parentRoute: typeof NewRouteRoute
    }
    '/old/': {
      id: '/old/'
      path: '/'
      fullPath: '/old/'
      preLoaderRoute: typeof OldIndexRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/old/source': {
      id: '/old/source'
      path: '/source'
      fullPath: '/old/source'
      preLoaderRoute: typeof OldSourceRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/v3/': {
      id: '/v3/'
      path: '/'
      fullPath: '/v3/'
      preLoaderRoute: typeof V3IndexRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/changelog': {
      id: '/v3/changelog'
      path: '/changelog'
      fullPath: '/v3/changelog'
      preLoaderRoute: typeof V3ChangelogRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/compare': {
      id: '/v3/compare'
      path: '/compare'
      fullPath: '/v3/compare'
      preLoaderRoute: typeof V3CompareRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/methodology': {
      id: '/v3/methodology'
      path: '/methodology'
      fullPath: '/v3/methodology'
      preLoaderRoute: typeof V3MethodologyRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/_app/benchmarks/': {
      id: '/_app/benchmarks/'
      path: '/benchmarks'
      fullPath: '/benchmarks/'
      preLoaderRoute: typeof AppBenchmarksIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/benchmarks/$id': {
      id: '/_app/benchmarks/$id'
      path: '/benchmarks/$id'
      fullPath: '/benchmarks/$id'
      preLoaderRoute: typeof AppBenchmarksIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/labs/': {
      id: '/_app/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof AppLabsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/labs/$id': {
      id: '/_app/labs/$id'
      path: '/labs/$id'
      fullPath: '/labs/$id'
      preLoaderRoute: typeof AppLabsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/': {
      id: '/_app/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models/$slug': {
      id: '/_app/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof AppModelsSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/news/$id': {
      id: '/_app/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof AppNewsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/leaderboard': {
      id: '/api/v1/leaderboard'
      path: '/api/v1/leaderboard'
      fullPath: '/api/v1/leaderboard'
      preLoaderRoute: typeof ApiV1LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old/models/$slug': {
      id: '/old/models/$slug'
      path: '/models/$slug'
      fullPath: '/old/models/$slug'
      preLoaderRoute: typeof OldModelsSlugRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/old/news/': {
      id: '/old/news/'
      path: '/news'
      fullPath: '/old/news/'
      preLoaderRoute: typeof OldNewsIndexRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/old/news/$id': {
      id: '/old/news/$id'
      path: '/news/$id'
      fullPath: '/old/news/$id'
      preLoaderRoute: typeof OldNewsIdRouteImport
      parentRoute: typeof OldRouteRoute
    }
    '/v3/benchmarks/': {
      id: '/v3/benchmarks/'
      path: '/benchmarks'
      fullPath: '/v3/benchmarks/'
      preLoaderRoute: typeof V3BenchmarksIndexRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/benchmarks/$id': {
      id: '/v3/benchmarks/$id'
      path: '/benchmarks/$id'
      fullPath: '/v3/benchmarks/$id'
      preLoaderRoute: typeof V3BenchmarksIdRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/labs/': {
      id: '/v3/labs/'
      path: '/labs'
      fullPath: '/v3/labs/'
      preLoaderRoute: typeof V3LabsIndexRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/labs/$id': {
      id: '/v3/labs/$id'
      path: '/labs/$id'
      fullPath: '/v3/labs/$id'
      preLoaderRoute: typeof V3LabsIdRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/models/': {
      id: '/v3/models/'
      path: '/models'
      fullPath: '/v3/models/'
      preLoaderRoute: typeof V3ModelsIndexRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/models/$slug': {
      id: '/v3/models/$slug'
      path: '/models/$slug'
      fullPath: '/v3/models/$slug'
      preLoaderRoute: typeof V3ModelsSlugRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/news/': {
      id: '/v3/news/'
      path: '/news'
      fullPath: '/v3/news/'
      preLoaderRoute: typeof V3NewsIndexRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/v3/news/$id': {
      id: '/v3/news/$id'
      path: '/news/$id'
      fullPath: '/v3/news/$id'
      preLoaderRoute: typeof V3NewsIdRouteImport
      parentRoute: typeof V3RouteRoute
    }
    '/api/admin/auth/$': {
      id: '/api/admin/auth/$'
      path: '/api/admin/auth/$'
      fullPath: '/api/admin/auth/$'
      preLoaderRoute: typeof ApiAdminAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppApiRoute: typeof AppApiRoute
  AppChangelogRoute: typeof AppChangelogRoute
  AppCompareRoute: typeof AppCompareRoute
  AppMethodologyRoute: typeof AppMethodologyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBenchmarksIdRoute: typeof AppBenchmarksIdRoute
  AppLabsIdRoute: typeof AppLabsIdRoute
  AppModelsSlugRoute: typeof AppModelsSlugRoute
  AppNewsIdRoute: typeof AppNewsIdRoute
  AppBenchmarksIndexRoute: typeof AppBenchmarksIndexRoute
  AppLabsIndexRoute: typeof AppLabsIndexRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppApiRoute: AppApiRoute,
  AppChangelogRoute: AppChangelogRoute,
  AppCompareRoute: AppCompareRoute,
  AppMethodologyRoute: AppMethodologyRoute,
  AppIndexRoute: AppIndexRoute,
  AppBenchmarksIdRoute: AppBenchmarksIdRoute,
  AppLabsIdRoute: AppLabsIdRoute,
  AppModelsSlugRoute: AppModelsSlugRoute,
  AppNewsIdRoute: AppNewsIdRoute,
  AppBenchmarksIndexRoute: AppBenchmarksIndexRoute,
  AppLabsIndexRoute: AppLabsIndexRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface NewRouteRouteChildren {
  NewSplatRoute: typeof NewSplatRoute
  NewIndexRoute: typeof NewIndexRoute
}

const NewRouteRouteChildren: NewRouteRouteChildren = {
  NewSplatRoute: NewSplatRoute,
  NewIndexRoute: NewIndexRoute,
}

const NewRouteRouteWithChildren = NewRouteRoute._addFileChildren(
  NewRouteRouteChildren,
)

interface OldRouteRouteChildren {
  OldSourceRoute: typeof OldSourceRoute
  OldIndexRoute: typeof OldIndexRoute
  OldModelsSlugRoute: typeof OldModelsSlugRoute
  OldNewsIdRoute: typeof OldNewsIdRoute
  OldNewsIndexRoute: typeof OldNewsIndexRoute
}

const OldRouteRouteChildren: OldRouteRouteChildren = {
  OldSourceRoute: OldSourceRoute,
  OldIndexRoute: OldIndexRoute,
  OldModelsSlugRoute: OldModelsSlugRoute,
  OldNewsIdRoute: OldNewsIdRoute,
  OldNewsIndexRoute: OldNewsIndexRoute,
}

const OldRouteRouteWithChildren = OldRouteRoute._addFileChildren(
  OldRouteRouteChildren,
)

interface V3RouteRouteChildren {
  V3ChangelogRoute: typeof V3ChangelogRoute
  V3CompareRoute: typeof V3CompareRoute
  V3MethodologyRoute: typeof V3MethodologyRoute
  V3IndexRoute: typeof V3IndexRoute
  V3BenchmarksIdRoute: typeof V3BenchmarksIdRoute
  V3LabsIdRoute: typeof V3LabsIdRoute
  V3ModelsSlugRoute: typeof V3ModelsSlugRoute
  V3NewsIdRoute: typeof V3NewsIdRoute
  V3BenchmarksIndexRoute: typeof V3BenchmarksIndexRoute
  V3LabsIndexRoute: typeof V3LabsIndexRoute
  V3ModelsIndexRoute: typeof V3ModelsIndexRoute
  V3NewsIndexRoute: typeof V3NewsIndexRoute
}

const V3RouteRouteChildren: V3RouteRouteChildren = {
  V3ChangelogRoute: V3ChangelogRoute,
  V3CompareRoute: V3CompareRoute,
  V3MethodologyRoute: V3MethodologyRoute,
  V3IndexRoute: V3IndexRoute,
  V3BenchmarksIdRoute: V3BenchmarksIdRoute,
  V3LabsIdRoute: V3LabsIdRoute,
  V3ModelsSlugRoute: V3ModelsSlugRoute,
  V3NewsIdRoute: V3NewsIdRoute,
  V3BenchmarksIndexRoute: V3BenchmarksIndexRoute,
  V3LabsIndexRoute: V3LabsIndexRoute,
  V3ModelsIndexRoute: V3ModelsIndexRoute,
  V3NewsIndexRoute: V3NewsIndexRoute,
}

const V3RouteRouteWithChildren =
  V3RouteRoute._addFileChildren(V3RouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  NewRouteRoute: NewRouteRouteWithChildren,
  OldRouteRoute: OldRouteRouteWithChildren,
  V3RouteRoute: V3RouteRouteWithChildren,
  SourceRoute: SourceRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiLedgerDotcsvRoute: ApiLedgerDotcsvRoute,
  ApiLedgerDotjsonRoute: ApiLedgerDotjsonRoute,
  ApiTRoute: ApiTRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiV1LeaderboardRoute: ApiV1LeaderboardRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiAdminAuthSplatRoute: ApiAdminAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
