/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SourceRouteImport } from './routes/source'
import { Route as ApiLedgerRouteImport } from './routes/api/ledger'
import { Route as ApiLedgerDotcsvRouteImport } from './routes/api/ledger[.]csv'
import { Route as ApiLedgerDotjsonRouteImport } from './routes/api/ledger[.]json'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1LeaderboardRouteImport } from './routes/api/v1/leaderboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerRoute = ApiLedgerRouteImport.update({
  id: '/api/ledger',
  path: '/api/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerDotcsvRoute = ApiLedgerDotcsvRouteImport.update({
  id: '/api/ledger.csv',
  path: '/api/ledger.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLedgerDotjsonRoute = ApiLedgerDotjsonRouteImport.update({
  id: '/api/ledger.json',
  path: '/api/ledger.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LeaderboardRoute = ApiV1LeaderboardRouteImport.update({
  id: '/api/v1/leaderboard',
  path: '/api/v1/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/source': typeof SourceRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/source': typeof SourceRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRouteWithChildren
  '/source': typeof SourceRoute
  '/api/ledger': typeof ApiLedgerRoute
  '/api/ledger.csv': typeof ApiLedgerDotcsvRoute
  '/api/ledger.json': typeof ApiLedgerDotjsonRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/api/v1/leaderboard': typeof ApiV1LeaderboardRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/news'
    | '/source'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/models/$slug'
    | '/news/$id'
    | '/api/v1/leaderboard'
    | '/api/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/news'
    | '/source'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/models/$slug'
    | '/news/$id'
    | '/api/v1/leaderboard'
    | '/api/v1'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/source'
    | '/api/ledger'
    | '/api/ledger.csv'
    | '/api/ledger.json'
    | '/models/$slug'
    | '/news/$id'
    | '/api/v1/leaderboard'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRouteWithChildren
  SourceRoute: typeof SourceRoute
  ApiLedgerRoute: typeof ApiLedgerRoute
  ApiLedgerDotcsvRoute: typeof ApiLedgerDotcsvRoute
  ApiLedgerDotjsonRoute: typeof ApiLedgerDotjsonRoute
  ModelsSlugRoute: typeof ModelsSlugRoute
  ApiV1LeaderboardRoute: typeof ApiV1LeaderboardRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger': {
      id: '/api/ledger'
      path: '/api/ledger'
      fullPath: '/api/ledger'
      preLoaderRoute: typeof ApiLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger.csv': {
      id: '/api/ledger.csv'
      path: '/api/ledger.csv'
      fullPath: '/api/ledger.csv'
      preLoaderRoute: typeof ApiLedgerDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ledger.json': {
      id: '/api/ledger.json'
      path: '/api/ledger.json'
      fullPath: '/api/ledger.json'
      preLoaderRoute: typeof ApiLedgerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/leaderboard': {
      id: '/api/v1/leaderboard'
      path: '/api/v1/leaderboard'
      fullPath: '/api/v1/leaderboard'
      preLoaderRoute: typeof ApiV1LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRouteWithChildren,
  SourceRoute: SourceRoute,
  ApiLedgerRoute: ApiLedgerRoute,
  ApiLedgerDotcsvRoute: ApiLedgerDotcsvRoute,
  ApiLedgerDotjsonRoute: ApiLedgerDotjsonRoute,
  ModelsSlugRoute: ModelsSlugRoute,
  ApiV1LeaderboardRoute: ApiV1LeaderboardRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
